<!DOCTYPE html>
<html>
<head>
    <title>数据库显示</title>
    <meta charset="utf-8">
    <style>
    table,th,td
{
    border:1px solid black;
}    
</style>
</head>
<body>
<table>
    <tr>
        <th>id</th>
        <th>title</th>
        <th>title_translation</th>
        <th>abstract</th>
        <th>abstract_translation</th>
        <th>year</th><th>url</th>
        <th>start_page</th>
        <th>end_page</th>
        <th>article_created_date</th>
        <th>article_last_updated</th>
        <th>journals_publisher</th>
        <th>journals_language</th>
        <th>journals_licenseId</th>
        <th>journals_title</th>
        <th>journals_country</th>
        <th>journals_number</th>
        <th>journals_volume</th>
        <th>journals_issns</th>
        <th>journals_create_date</th>
        <th>term</th>
        <th>term_code</th>
        <th>term_l1</th>
        <th>keyword</th>
        <th>keyword_translation</th>
        <th>author_name</th>
        <th>author_affiliation</th>
        <th>author_email</th>
        <th>identifier_type</th>
        <th>identifier_identifierId</th>
        <th>license_type</th>
        <th>license_title</th>
        <th>license_url</th>
    </tr>
</table>
</body>
</html>